TEXT_TO_FIND: str = "Make Appointment"
MEDICAL_CENTER_URL: str = "https://katalon-demo-cura.herokuapp.com/"
BTN_MAKE_APPOINTMENT_TEXT: str = "Make Appointment"
USER_NAME: str = "User name"
USER_PASSWORD: str = "1a2b3c4d"
